import os
import psycopg2
from typing import Optional
from fastapi import FastAPI, HTTPException, Query
from pydantic import BaseModel, Field
from prometheus_fastapi_instrumentator import Instrumentator

app = FastAPI(title="Smart Industrial PySpark Predictive Maintenance API", version="1.0.0")
Instrumentator().instrument(app).expose(app)
DB_CONFIG = {"host":os.getenv("POSTGRES_HOST","postgres"),"port":os.getenv("POSTGRES_PORT","5432"),"dbname":os.getenv("POSTGRES_DB","industrial"),"user":os.getenv("POSTGRES_USER","industrial"),"password":os.getenv("POSTGRES_PASSWORD","industrial")}

class PredictionInput(BaseModel):
    temperature: float = Field(..., ge=-20, le=150)
    vibration: float = Field(..., ge=0)
    pressure: float = Field(..., gt=0)
    rpm: float = Field(..., ge=0)
    current: float = Field(..., ge=0)
    humidity: float = Field(..., ge=0, le=100)
    operating_hours: float = Field(..., ge=0)

def db():
    try: return psycopg2.connect(**DB_CONFIG)
    except psycopg2.Error as exc: raise HTTPException(status_code=503, detail=f"Database unavailable: {exc}")

@app.get("/")
def root(): return {"name":"Smart Industrial PySpark Predictive Maintenance API","docs":"/docs","health":"/api/health"}

@app.get("/api/health")
def health():
    c=db(); c.close(); return {"status":"healthy"}

@app.get("/api/machines")
def machines():
    c=db()
    try:
        with c.cursor() as cur:
            cur.execute("SELECT DISTINCT machine_id FROM machine_predictions ORDER BY machine_id")
            return {"machines":[r[0] for r in cur.fetchall()]}
    finally: c.close()

@app.get("/api/summary")
def summary():
    c=db()
    try:
        with c.cursor() as cur:
            cur.execute("""SELECT COUNT(*), COUNT(DISTINCT machine_id), AVG(failure_probability), SUM(CASE WHEN risk_level='HIGH' THEN 1 ELSE 0 END), SUM(CASE WHEN risk_level='MEDIUM' THEN 1 ELSE 0 END), SUM(CASE WHEN risk_level='LOW' THEN 1 ELSE 0 END) FROM machine_predictions""")
            r=cur.fetchone()
            return {"predictions":r[0],"machines":r[1],"average_failure_probability":r[2],"high_risk":r[3],"medium_risk":r[4],"low_risk":r[5]}
    finally: c.close()

@app.get("/api/predictions")
def predictions(machine_id: Optional[str]=Query(None), limit: int=Query(50, ge=1, le=1000)):
    c=db()
    try:
        with c.cursor() as cur:
            if machine_id:
                cur.execute("SELECT id,machine_id,prediction,failure_probability,risk_level,temperature,vibration,pressure,rpm,current,humidity,operating_hours,predicted_at FROM machine_predictions WHERE machine_id=%s ORDER BY predicted_at DESC LIMIT %s", (machine_id,limit))
            else:
                cur.execute("SELECT id,machine_id,prediction,failure_probability,risk_level,temperature,vibration,pressure,rpm,current,humidity,operating_hours,predicted_at FROM machine_predictions ORDER BY predicted_at DESC LIMIT %s", (limit,))
            cols=[d[0] for d in cur.description]
            return [dict(zip(cols,row)) for row in cur.fetchall()]
    finally: c.close()

@app.post("/api/predict")
def predict(data: PredictionInput):
    score=sum([data.temperature>=70,data.vibration>=3,data.pressure>=105,data.current>=11.5,data.operating_hours>=7500])
    probability=min(0.05+score*0.20,0.95)
    risk="HIGH" if probability>=0.80 else "MEDIUM" if probability>=0.50 else "LOW"
    return {"prediction":int(probability>=0.50),"failure_probability":round(probability,4),"risk_level":risk,"note":"Batch production predictions are generated by the PySpark ML pipeline."}
