services:

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: smartmlops
      POSTGRES_USER: mlops
      POSTGRES_PASSWORD: mlops
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlops -d smartmlops"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped


  opcua-server:
    build:
      context: .
      dockerfile: Dockerfile.opcua
    ports:
      - "4841:4840"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket; s=socket.create_connection(('localhost',4840),2); s.close()\""]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped


  collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    environment:
      DATABASE_URL: postgresql://mlops:mlops@postgres:5432/smartmlops
      OPCUA_ENDPOINT: opc.tcp://opcua-server:4840/freeopcua/server/
      OPCUA_NODE_ID: ns=2;s=Machine.Temperature
    depends_on:
      postgres:
        condition: service_healthy
      opcua-server:
        condition: service_healthy
    restart: unless-stopped


  trainer:
    build:
      context: .
      dockerfile: Dockerfile.trainer
    environment:
      DATABASE_URL: postgresql://mlops:mlops@postgres:5432/smartmlops
      MODEL_PATH: /app/models/temperature_model.joblib
      REFERENCE_PATH: /app/models/reference.csv
    volumes:
      - ./models:/app/models
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - python
      - -m
      - ml.train


  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      DATABASE_URL: postgresql://mlops:mlops@postgres:5432/smartmlops
      MODEL_PATH: /app/models/temperature_model.joblib
    volumes:
      - ./models:/app/models
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped


  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    environment:
      DATABASE_URL: postgresql://mlops:mlops@postgres:5432/smartmlops
      REFERENCE_PATH: /app/models/reference.csv
      DRIFT_WINDOW: "100"
      DRIFT_P_VALUE: "0.01"
      RETRAIN_COOLDOWN_SECONDS: "300"
    volumes:
      - ./models:/app/models
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped


  prometheus:
    image: prom/prometheus:v3.5.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - api
      - monitor
    restart: unless-stopped


  grafana:
    image: grafana/grafana:12.1.1
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafanadata:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    restart: unless-stopped


volumes:
  pgdata:
  grafanadata: