FROM apache/spark:3.5.3-python3

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        python3-pip && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN python3 -m pip install --upgrade pip setuptools wheel && \
    python3 -m pip install --no-cache-dir --prefer-binary -r /app/requirements.txt

RUN curl -L \
    https://jdbc.postgresql.org/download/postgresql-42.7.4.jar \
    -o /opt/spark/jars/postgresql-42.7.4.jar

COPY pyspark /app/pyspark

RUN mkdir -p \
    /app/data/raw \
    /app/data/processed \
    /app/data/features \
    /app/models

ENV PYTHONUNBUFFERED=1

CMD ["python3", "/app/pyspark/etl.py"]